# Generated by Django 4.2.29 on 2026-04-17 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(help_text='Ej: A-12, Cabaña 3, Pieza 7', max_length=50)),
                ('unit_type', models.CharField(choices=[('apartment', 'Departamento'), ('room', 'Pieza'), ('cabin', 'Cabaña'), ('house', 'Casa'), ('office', 'Oficina'), ('other', 'Otro')], default='apartment', max_length=20)),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('occupied', 'Ocupado'), ('maintenance', 'Mantención')], default='available', max_length=20)),
                ('floor', models.CharField(blank=True, max_length=10)),
                ('area_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='organizations.organization')),
            ],
            options={
                'ordering': ['identifier'],
                'unique_together': {('organization', 'identifier')},
            },
        ),
    ]
